
title: Online Multimodal Knowledge Discovery

copyright: Copyright © 2020

description: >- # this means to ignore newlines until "baseurl:"
  Online Multimodal Knowledge Discovery
  at ICDM 2020: 20th IEEE International Conference on Data Mining.

baseurl: ""
url: "https://multimodal-knowledge-discovery.github.io/"

theme: jekyll-theme-cayman

markdown: kramdown

plugins:
  - jekyll-spaceship